version: '3.2'
services:
 
    kl-center-srv:
        build:
            context: .
            dockerfile: DockerfileCenterService

        image: kl-center-srv
        container_name: kl-center-srv

        hostname: kl-center-srv
        user: root
        restart: always
        ports:
            - '12340:12340' 
        #command:
        environment:
            APP_OPTS: --spring.profiles.active=dev
            DUBBO_IP_TO_REGISTRY: 120.78.136.63
        volumes:
            - /etc/localtime:/etc/localtime:ro
            #- /etc/hosts:/etc/hosts:ro
            - /opt/logs/center:/opt/logs/center
            - /tmp:/tmp
        extra_hosts:
            - "mysql.kunlong.com:172.17.0.1"
            - "redis.kunlong.com:172.17.0.1"
            - "zookeeper.kunlong.com:172.17.0.1"
            
    kl-pf-ctl:
        build:
            context: .
            dockerfile: DockerfilePfCtrl

        image: kl-pf-ctl
        container_name: kl-pf-ctl

        hostname: kl-pf-ctl
        user: root
        restart: always
        ports:
            - '10080:10080' 
            - '12341:12341'
        #command:
        environment:
            APP_OPTS: --spring.profiles.active=dev
            DUBBO_IP_TO_REGISTRY: 120.78.136.63
        volumes:
            - /etc/localtime:/etc/localtime:ro
            #- /etc/hosts:/etc/hosts:ro
            - /opt/logs/platform:/opt/logs/pf
            - /tmp:/tmp
        extra_hosts:
            - "mysql.kunlong.com:172.17.0.1"
            - "redis.kunlong.com:172.17.0.1"
            - "zookeeper.kunlong.com:172.17.0.1"

    kl-dongxw-ctl:
        build:
            context: .
            dockerfile: DockerfileDongxwCtrl

        image: kl-dongxw-ctl
        container_name: kl-dongxw-ctl

        hostname: kl-dongxw-ctl
        user: root
        restart: always
        ports:
            - '10081:10081' 
        #command:
        environment:
            APP_OPTS: --spring.profiles.active=dev
            DUBBO_IP_TO_REGISTRY: 120.78.136.63
        volumes:
            - /etc/localtime:/etc/localtime:ro
            #- /etc/hosts:/etc/hosts:ro
            - /opt/logs/dongxw:/opt/logs/dongxw
            - /tmp:/tmp
        extra_hosts:
            - "mysql.kunlong.com:172.17.0.1"
            - "redis.kunlong.com:172.17.0.1"
            - "zookeeper.kunlong.com:172.17.0.1"

    kl-customer-app:
        build:
            context: .
            dockerfile: DockerfileCustomerApp

        image: kl-customer-app
        container_name: kl-customer-app

        hostname: kl-customer-app
        user: root
        restart: always
        ports:
            - '10082:10082'
        #command:
        environment:
            APP_OPTS: --spring.profiles.active=dev
            DUBBO_IP_TO_REGISTRY: 120.78.136.63
        volumes:
            - /etc/localtime:/etc/localtime:ro
            #- /etc/hosts:/etc/hosts:ro
            - /opt/logs/customer:/opt/logs/customer
        extra_hosts:
            - "mysql.akunlong.top:172.17.0.1"
            - "redis.akunlong.top:172.17.0.1"
            - "zookeeper.akunlong.top:172.17.0.1"                        
